version: '3'
services:
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'root'
            MYSQL_PASS: 'root'
        volumes:
        - ./src/main/resources/sql:/docker-entrypoint-initdb.d
        - ./docker_db_data/mariadb:/var/lib/mysql # creating this folder for persisting data of the mariadb in your host
        ports:
        - "3306:3306"
        networks:
        - app_net
        container_name: mydb
    web-app:
        build: .
        volumes:
        - .:/JavaChatBoard
        working_dir: /
        ports:
        - "8080:8080"
        stdin_open: true
        tty: true
        depends_on:
        - db
        container_name: webapp
        networks:
        - app_net
networks:
    # Containers in same network can access each other by using its container name as host name
    app_net:
        driver: "bridge"
